- name: "AgentService"
  color: "D4C5F9"
  description: "Issues affecting Chocolatey Agent Windows Service (chocolatey-agent)."
- name: "CentralManagement"
  color: "D4C5F9"
  description: "Issues affecting Chocolatey Central Management."
- name: "GuiExtension"
  color: "D4C5F9"
  description: "Issues affecting the Chocolatey GUI Licensed Extension (chocolateygui.extension)."
  aliases: ["ChocolateyGuiExtension"]
- name: "Edition - Architect"
  color: "006B75"
- name: "Edition - Business"
  color: "006B75"
- name: "Edition - MSP"
  color: "006B75"
- name: "Edition - Pro"
  color: "006B75"
- name: "LicensedExtension"
  color: "D4C5F9"
  description: "Issues affecting the Chocolatey
  Licensed Extension (chocolatey.extension)."
- name: "NEEDS_PRIORITIZED_INTERNAL"
  color: "E11D21"
  description: "These are issues that need prioritized, and may need an internal facing issue created."